extends:
  - spectral:oas

rules:
  # Ensure descriptions exist on operations
  operation-description: warn

  # Ensure API servers are defined
  oas3-api-servers: error

  # Ensure operation IDs are unique
  operation-operationId-unique: error

  # Enforce contact and license info for production API documentation
  info-contact: warn
  info-license: warn

  # Enforce valid OpenAPI schema
  oas3-schema: error
