extends:
  - spectral:oas

rules:
  # Ensure descriptions exist on operations
  operation-description: warn

  # Ensure API servers are defined
  oas3-api-servers: error

  # Ensure operation IDs are unique
  operation-operationId-unique: error

  # Allow info.contact to be optional
  info-contact: off

  # Allow info.license to be optional
  oas3-schema: warn
