/**
 * OpenAPI spec is now auto-generated by @fastify/swagger from route schemas.
 *
 * - Serve live: GET /docs (Swagger UI) and GET /docs/json (raw spec)
 * - Generate static file: npm run openapi:generate → docs/openapi.json
 * - Lint: npm run openapi:lint
 *
 * This file is kept as documentation only. The manual spec object has been removed.
 */
