/**
 * Branded Types for Type-Safe Identifiers
 *
 * AUDIT-FIX: This file now re-exports from the canonical source at
 * packages/kernel/validation/branded.ts to eliminate code duplication.
 * All branded type definitions and factory functions are maintained there.
 */

// Re-export everything from the canonical source
export type {
  Brand,
  Branded,
  OrgId,
  UserId,
  ExperimentId,
  MembershipId,
  DomainId,
  DomainRegistryId,
  ContentId,
  ContentVersionId,
  ContentIdeaId,
  MediaAssetId,
  MediaCollectionId,
  EmailSubscriberId,
  EmailCampaignId,
  EmailTemplateId,
  JobId,
  TaskId,
  ExportId,
  AnalyticsEventId,
  MetricId,
  ReportId,
  SubscriptionId,
  InvoiceId,
  PaymentId,
  AffiliateId,
  CommissionId,
  KeywordId,
  AuditEventId,
  SessionId,
  ApiKeyId,
  CustomerId,
  PublishingJobId,
  NotificationId,
  SearchIndexId,
  IndexingJobId,
  AuthorId,
  RevisionId,
  CommentId,
  WebhookId,
} from './validation/branded';

export {
  createOrgId,
  createUserId,
  createExperimentId,
  createDomainId,
  createContentId,
  createEmailSubscriberId,
  createJobId,
  createPaymentId,
  createSubscriptionId,
  createMediaAssetId,
  createAuditEventId,
  createSessionId,
  createCustomerId,
  createInvoiceId,
  createPublishingJobId,
  createNotificationId,
  createSearchIndexId,
  createIndexingJobId,
  createAuthorId,
  createRevisionId,
  createCommentId,
  createWebhookId,
  createApiKeyId,
  createKeywordId,
  unsafeBrand,
  isValidId,
  isOrgId,
  isUserId,
  isDomainId,
  isContentId,
  isCustomerId,
  isInvoiceId,
  isPaymentId,
  unsafeAsUserId,
  unsafeAsOrgId,
  unsafeAsContentId,
  unsafeAsDomainId,
} from './validation/branded';
